import Script from 'next/script';
import Head from "next/head";

const Root = (props) => {
  return (
    <>
      <Head>
        <title>Books</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js" />
        {/* <Script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.2.0/js/fontawesome.min.js" /> */}
      {/* <NavBar isAuthenticated={isAuthenticated} /> */}
    </>
    
    // <h3 style={{textAlign: 'center'}}>Welcome To Book App!!! <br /> Please <Link style={{textDecoration: 'unset'}} href='/login'>Login</Link> to Find Books</h3>
  );
};

export default Root;
